Attempt to fix the ruby head build
Always install bundler so it gets updated. This will fix the ruby-head
build that's failing on master and 1-6-stable with

```
bundler: failed to load command: rake
(/home/travis/build/rack/rack/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
```